source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!
platform:ios, '9.0'

abstract_target '_' do

    pod 'ReactiveObjC'
    pod 'IAPHelper'       #https://github.com/saturngod/IAPHelper
    pod 'YYModel'         #https://github.com/ibireme/YYModel
    pod 'YYCategories'
    pod 'YYCache'
    pod 'MBProgressHUD'     #http://www.bukovinski.com
    pod 'DZNEmptyDataSet'   #https://github.com/dzenbot/DZNEmptyDataSet
    pod 'FMDB/standalone'              #https://github.com/ccgus/fmdb
    pod 'MJRefresh'                     #https://github.com/CoderMJLee/MJRefresh
    pod 'hpple', :git => 'https://github.com/topfunky/hpple.git'             #https://github.com/topfunky/hpple
    pod 'DGActivityIndicatorView'  #https://github.com/gontovnik/DGActivityIndicatorView
    pod 'PinYin4Objc'              #https://github.com/kimziv/PinYin4Obj
    pod 'JZNavigationExtension', '1.5.0.1' #https://github.com/JazysYu/JZNavigationExtension
    pod 'AMPopTip'          #https://github.com/andreamazz/AMPopTip
    pod 'SAMKeychain'
    pod 'DZNWebViewController'          #https://github.com/dzenbot/DZNWebViewController
    pod 'DACircularProgress'
    pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
    pod 'IQKeyboardManager'
    pod 'SDWebImage/GIF'
    pod 'SDWebImage/WebP'
    pod 'AFNetworking'
    pod 'SSZipArchive'
    pod 'AVOSCloud'
    pod 'Bugly'
    pod 'Hero'

    pod 'IDMPhotoBrowser', :git => 'https://github.com/developforapple/IDMPhotoBrowser.git'
    pod 'JBChartView' , :git => 'https://github.com/developforapple/JBChartView.git'
    pod 'ChameleonFramework'
    pod 'MXParallaxHeader'
    pod 'FCUUID'

    target 'SPDev' do
        pod 'Google-Mobile-Ads-SDK'
    end

    target 'SPAd' do
        pod 'Google-Mobile-Ads-SDK'
    end

    target 'SPOld' do
        pod 'Google-Mobile-Ads-SDK'
    end

    target 'SPPro' do

    end

end

targetsArray = ['SPDev', 'SPPro', 'SPAd', 'SPOld']

def setup_target_macro(ttargets)
    puts "设置所有 Target 的预编译宏"
    _xcode_project_path = Dir.glob("*.xcodeproj").first
    app_project = Xcodeproj::Project.open(_xcode_project_path)

    app_project.native_targets.each do |target|
        puts "Target #{target.name}"
        if ttargets.include?(target.name)
            _MACRO_STR = 'TARGET_' + target.name + '=1'
            puts "添加: #{_MACRO_STR}"
            target.build_configurations.each do |config|
                _tempDefinitions = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'];
                _tempDefinitions |= [_MACRO_STR]
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = _tempDefinitions;

                if !config.base_configuration_reference
                    app_project.save
                elsif File.exist?(config.base_configuration_reference.path)
                    _GCCProprogressSTR = 'GCC_PREPROCESSOR_DEFINITIONS = ' + config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'].join(" ")
                    text = File.read(config.base_configuration_reference.path)
                    match = /^GCC_PREPROCESSOR_DEFINITIONS.*$/.match(text)
                    if match[0]
                        text = text.gsub(match[0],_GCCProprogressSTR)
                        File.open(config.base_configuration_reference.path, "w") { |file| file.puts text}
                    end
                end
            end
        end
    end
end

post_install do |installer|

    setup_target_macro targetsArray

    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
#            config.build_settings['SWIFT_VERSION'] = '4.2'
            config.build_settings['VALID_ARCHS'] = 'armv7 arm64'
            config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = false
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
            
            # 解决 AVOSCloud 中无法使用sqlite3.framework的问题
            if config.build_settings['PRODUCT_NAME'] == 'AVOSCloud'
                config.build_settings['FRAMEWORK_SEARCH_PATHS'] = "$(inherited) $PODS_CONFIGURATION_BUILD_DIR/sqlite3"
                config.build_settings['OTHER_CFLAGS'] = "$(inherited) -DFMDB_SQLITE_STANDALONE"
            end
        end
    end
end
